# Generated by Django 5.2.5 on 2025-10-30 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=200, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('is_duplicate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('used_for', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('open', 'Open'), ('settled', 'Settled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_liabilities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_liabilities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('requested', 'requested'), ('authorized', 'authorized'), ('debit_processing', 'debit_processing'), ('debit_succeeded', 'debit_succeeded'), ('payment_failed', 'payment_failed'), ('transfer_created', 'transfer_created'), ('transfer_failed', 'transfer_failed'), ('payout_paid', 'payout_paid'), ('payout_failed', 'payout_failed')], default='requested', max_length=30)),
                ('payment_intent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transfer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payout_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transfer_group', models.CharField(blank=True, max_length=100, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['state'], name='payments_wi_state_75265d_idx'), models.Index(fields=['payment_intent_id'], name='payments_wi_payment_161636_idx'), models.Index(fields=['transfer_id'], name='payments_wi_transfe_2c59e5_idx'), models.Index(fields=['payout_id'], name='payments_wi_payout__6261d6_idx')],
            },
        ),
    ]
