# Generated by Django 5.2.5 on 2025-10-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralreward',
            name='redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
