# Generated by Django 5.2.5 on 2025-09-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='permission_concent',
            field=models.BooleanField(default=False),
        ),
    ]
