# Generated by Django 5.2.5 on 2025-09-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referr', '0002_referral_permission_concent'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='reference_id',
            field=models.CharField(default='', editable=False, max_length=20, unique=True),
        ),
    ]
