# Generated by Django 5.2.5 on 2025-09-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referr', '0003_referralreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='reward_given',
            field=models.BooleanField(default=False),
        ),
    ]
