# Generated by Django 5.2.5 on 2025-09-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referr', '0004_referral_reward_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='is_to_be_registered',
            field=models.BooleanField(default=False),
        ),
    ]
