# Generated by Django 5.2.5 on 2025-09-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referr', '0005_referral_is_to_be_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='is_to_be_registered',
        ),
    ]
