# Generated by Django 5.2.5 on 2025-10-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referr', '0006_remove_referral_is_to_be_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralreward',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='referralreward',
            name='withdrawal_status',
            field=models.BooleanField(default=False),
        ),
    ]
