# Generated by Django 5.2.5 on 2025-09-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referr', '0006_alter_referralassignment_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralassignment',
            name='status',
        ),
        migrations.AddField(
            model_name='referral',
            name='approval',
            field=models.CharField(default='reject', max_length=20),
        ),
    ]
