# Generated by Django 5.2.5 on 2025-09-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referr', '0007_remove_referralassignment_status_referral_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='approval',
        ),
        migrations.AddField(
            model_name='referral',
            name='company_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_by_approval',
            field=models.BooleanField(default=False),
        ),
    ]
