# Generated by Django 5.2.5 on 2025-10-01 18:22

import django.db.models.deletion
import utils.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_dimensions_message_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file_url',
        ),
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=utils.storage_backends.MediaStorage(), upload_to='chat_files/'),
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(storage=utils.storage_backends.MediaStorage(), upload_to='chat_files/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('file_type', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('dimensions', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_attachments', to='chat.message')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
