# Generated by Django 5.2.5 on 2025-09-14 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_referral_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(blank=True, max_length=20, null=True)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, help_text='Where the referral code was used (e.g., signup, purchase)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this referral usage', null=True)),
                ('used_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_referrals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
