# Generated by Django 5.2.5 on 2025-09-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_to_be_registered',
            field=models.BooleanField(default=False),
        ),
    ]
