# Generated by Django 5.2.5 on 2025-10-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Whether the device is currently online/app is open'),
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Last time the device was seen online', null=True),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'is_online'], name='accounts_de_user_id_9e5b78_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['last_seen'], name='accounts_de_last_se_b48553_idx'),
        ),
    ]
