# Generated by Django 5.2.5 on 2025-10-11 20:29

import django.db.models.deletion
import utils.storage_backends
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_device_is_online_device_last_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_platform',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_rating', models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('review_feedback', models.TextField(blank=True, help_text='Written feedback about the business', null=True)),
                ('review_by_name', models.CharField(help_text='Name of the person who gave the review', max_length=150)),
                ('review_by_image', models.URLField(blank=True, help_text='Profile image URL of the reviewer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(limit_choices_to={'role': 'company'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
                ('review_by', models.ForeignKey(limit_choices_to={'role': 'solo'}, on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Review image stored in S3', storage=utils.storage_backends.MediaStorage(), upload_to='review_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_gallery', to='accounts.review')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['business', 'created_at'], name='accounts_re_busines_2f4bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['review_by', 'created_at'], name='accounts_re_review__08766a_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['review_rating'], name='accounts_re_review__0dba1f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('review_by', 'business')},
        ),
        migrations.AddIndex(
            model_name='reviewimage',
            index=models.Index(fields=['review', 'uploaded_at'], name='accounts_re_review__59b120_idx'),
        ),
    ]
