# Generated by Django 5.2.5 on 2025-10-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_social_platform_review_reviewimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='abg_rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
