# Generated by Django 5.2.5 on 2025-10-21 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_businessinfo_abg_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessinfo',
            old_name='abg_rating',
            new_name='avg_rating',
        ),
    ]
